name: Automatisation des tests DevSecOps
on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Installation de Trivy
        uses: aquasecurity/trivy-action@master
          
      - name: 1° - Contrôle des dépendances (requirements.txt) avec Trivy
        run: |
          echo "Démarrage de l'analyse des dépendances (requirements.txt) avec Trivy..."
          # Exécute le scan SANS --exit-code 1 pour garantir l'affichage du rapport
          # Le rapport est enregistré dans un fichier temporaire
          trivy fs --format json --security-checks vuln requirements.txt > trivy_report_deps.json
          
          # Affiche le rapport complet dans les logs (utile pour le debug)
          cat trivy_report_deps.json
          
          # Utilise 'trivy' pour vérifier le rapport et le faire échouer uniquement si des problèmes sont trouvés.
          # Cette technique garantit que l'output est produit AVANT l'échec.
          tivy fs --exit-code 1 --severity CRITICAL,HIGH --security-checks vuln requirements.txt
          echo "Analyse des dépendances terminée."

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Installation de Trivy
        uses: aquasecurity/trivy-action@master

      - name: 2° - Contrôle du Dockerfile avec Trivy (Misconfigurations)
        run: |
          echo "Démarrage de l'analyse du Dockerfile pour les mauvaises configurations (misconfigurations) avec Trivy..."
          # Exécute le scan SANS --exit-code 1
          trivy config --format json Dockerfile > trivy_report_docker.json
          
          # Affiche le rapport complet
          cat trivy_report_docker.json
          
          # Utilise 'trivy' pour vérifier le rapport et le faire échouer uniquement si des problèmes sont trouvés.
          trivy config --exit-code 1 Dockerfile
          echo "Analyse du Dockerfile terminée."
          
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
