name: Automatisation des tests DevSecOps
on: push

jobs:

  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan requirements.txt avec Trivy
        run: |
          mkdir -p $HOME/.cache/trivy
          docker run --rm \
            -v "${{ github.workspace }}":/project \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:latest fs /project/requirements.txt


  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build de l'image Docker
        run: |
          docker build -t imgvulne:1.1 .

      - name: Scan de l'image Docker avec Trivy
        run: |
          mkdir -p $HOME/.cache/trivy

          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:latest image --format json --severity HIGH,CRITICAL imgvulne:1.1 \
          | jq -r '
            ["TARGET","PACKAGE","INSTALLED","VULN","SEVERITY"],
            (.Results[]? as $r | $r.Vulnerabilities[]? 
              | [$r.Target, .PkgName, .InstalledVersion, .VulnerabilityID, .Severity]) 
            | @tsv' \
          | column -t -s $'\t'


  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: echo "✔ Déploiement possible : les scans sont OK"
