name: Automatisation des tests DevSecOps
on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Installation de Trivy
        # Utilisation de l'action officielle de Trivy pour une installation facile
        uses: aquasecurity/trivy-action@master
          
      - name: 1° - Contrôle des dépendances (requirements.txt) avec Trivy
        run: |
          echo "Démarrage de l'analyse des dépendances (requirements.txt) avec Trivy..."
          # L'option --exit-code 1 est maintenue pour garantir l'échec si des vulnérabilités sont trouvées.
          trivy fs --format table --exit-code 1 --security-checks vuln requirements.txt
          echo "Analyse des dépendances terminée. Succès si aucune vulnérabilité trouvée."

  Dockerfile:
    runs-on: ubuntu-latest
    # Le job ne s'exécute que si 'Dependances' réussit
    needs: Dependances
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Installation de Trivy
        uses: aquasecurity/trivy-action@master

      - name: 2° - Contrôle du Dockerfile avec Trivy (Misconfigurations)
        run: |
          echo "Démarrage de l'analyse du Dockerfile pour les mauvaises configurations (misconfigurations) avec Trivy..."
          # Scan des erreurs de configuration du Dockerfile avec échec si un problème est détecté.
          trivy config --exit-code 1 Dockerfile
          echo "Analyse du Dockerfile terminée. Succès si pas de mauvaises configurations."
          
  Deploy:
    runs-on: ubuntu-latest
    # Le job ne s'exécute que si 'Dockerfile' réussit
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
