name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: 1° - Analyse des dépendances (requirements.txt)
        run: |
          echo "Analyse des dépendances…"
          trivy fs --exit-code 1 --severity HIGH,CRITICAL requirements.txt
          echo "Analyse OK"

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: 2° - Analyse du Dockerfile (misconfigurations)
        run: |
          echo "Analyse du Dockerfile…"
          trivy config --severity HIGH,CRITICAL --exit-code 1 Dockerfile
          echo "Analyse OK"

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: echo "Déploiement prêt."
